config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all
  end
  def new
    @project= Project.new
  end
  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice]= "Project has been created."
      redirect_to @project
    else
      flash.now[:alert]= "Project has not been created."
      render "new"
    end
  end
  def show
    @project = Project.find(params[:id])
  end
  def edit
    @project = Project.find(params[:id])

  end
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice]= "Project has been updated."
      redirect_to @project
    else
      flash.now[:alert] ="Project has not been updated."
      render "edit"
    end
  end
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice]= "Project has been deleted."
    redirect_to projects_path
  end
end

private
def project_params
  params.require(:project).permit(:name,:description)
end
def set_project
  @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
   <% if content_for?(:title) %>
   <%= yield (:title) %>
   <% else %>
   Ticketee
   <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key,message| %>
<div><%= message %> </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for project do |f| %>
<% if project.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(project.errors.count,"error") %>
    prohibited this project from being saved</h2>
  <ul>
    <% project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.label :name %><br>
<%= f.text_field :name, class: "form-control" %>
<%= f.label :description %><br>
<%= f.text_field :description, class: "form-control" %>
<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
<div id="projects">
  <% @projects.each do |project| %>
  <h2>
    <%= link_to  project.name, project %>
  </h2>
  <p>
    <%= project.description %>
  </p>
 <% end %>
</div>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@project.errors.count,"error") %>
    prohibited this project from being saved</h2>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.label :name %><br>
<%= f.text_field :name, class: "form-control" %>
<%= f.label :description %><br>
<%= f.text_field :description, class: "form-control" %>
<%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<%= title(@project.name,"Projects") %>
<h1><%= @project.name %></h1>
<p><%= @project.description %></p>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project",project_path(@project),method: :delete,
data: { confirm: "Are you sure you want to delete this project?" } %>